#!/usr/bin/bash
MESA_NO_ERROR=1 MESA_GL_VERSION_OVERRIDE=4.5 MESA_GLES_VERSION_OVERRIDE=3.2 GALLIUM_DRIVER=zink ZINK_DESCRIPTORS=auto virgl_test_server --use-egl-surfaceless --use-gles &
#virgl_test_server_android &
