#!/data/data/com.termux/files/usr/bin/bash
#am start --user 0 -n com.termux/com.termux.app.TermuxActivity


am start --user 0 -n com.termux.x11/com.termux.x11.MainActivity > /dev/null 2>&1
sleep 1

~/desktop

sleep 1
GALLIUM_DRIVER=zink DISPLAY=:0 chromium-browser 2> /dev/null 


pkill openbox

am broadcast -a com.termux.x11.ACTION_STOP -p com.termux.x11 > /dev/null 2>&1

exit 0
