#!/data/data/com.termux/files/usr/bin/bash

# Kill open X11 processes

cleanup() {
	kill -9 $(pgrep -f "termux.x11") 2>/dev/null
	kill -9 $(pgrep -f "pulseaudio") >/dev/null
	kill -9 $(pgrep -f "virgl_test_server") >/dev/null
	exit 0
}

trap cleanup SIGINT

# Enable PulseAudio over Network
#LD_PRELOAD=/system/lib64/libskcodec.so
#sh ./gpu
#sleep 1

pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1

# Prepare termux-x11 session
export XDG_RUNTIME_DIR=${TMPDIR}
termux-x11 :0 >/dev/null &

# Wait a bit until termux-x11 gets started.
sleep 3

# Launch Termux X11 main activity
am start --user 0 -n com.termux.x11/com.termux.x11.MainActivity > /dev/null 2>&1
sleep 1

# Login in PRoot Environment. Do some initialization for PulseAudio, /tmp directory
# and run XFCE4 as user droidmaster.
# See also: https://github.com/termux/proot-distro
# Argument -- acts as terminator of proot-distro login options processing.
# All arguments behind it would not be treated as options of PRoot Distro.
#
proot-distro login   --bind ~/something:/proc/bus/pci/devices --bind ~/fake_shm:/dev/shm debian --shared-tmp -- /bin/bash -c  'export PULSE_SERVER=127.0.0.1 && export XDG_RUNTIME_DIR=${TMPDIR} && su - user -c "env DISPLAY=:0 dbus-launch --exit-with-session  startxfce4"'


# proot-distro login   --bind ~/something:/proc/bus/pci/devices --bind ~/fake_shm:/dev/shm debian --shared-tmp -- /bin/bash -c  'export PULSE_SERVER=127.0.0.1 && export XDG_RUNTIME_DIR=${TMPDIR} && su - user -c "env DISPLAY=:0 GALLIUM_DRIVER=zink MESA_GL_VERSION_OVERRIDE=4.0 dbus-launch --exit-with-session  startxfce4"'

# proot-distro login   --bind ~/something:/proc/bus/pci/devices --bind ~/fake_shm:/dev/shm debian --shared-tmp -- /bin/bash -c  'export PULSE_SERVER=127.0.0.1 && export XDG_RUNTIME_DIR=${TMPDIR} && su - user -c "env DISPLAY=:0 startxfce4"'

am broadcast -a com.termux.x11.ACTION_STOP -p com.termux.x11 > /dev/null 2>&1
cleanup
exit 0
